### ISSUE TITLE
Please delete the Sales Data Exploration file as it is near-duplicate

### ISSUE THREAD

**Issue by siraj-samsudeen** [talkpython/excel-to-python-course#2]
https://github.com/talkpython/excel-to-python-course/blob/master/code/ch4-intro-to-pandas/Sales-Analysis-Exploration.ipynb

This file is almost a duplicate of the other file in the folder - the other file has proper comments. Hence, this can be deleted.

**Comment by mikeckennedy** [comment]
Thanks @siraj-samsudeen I believe @chris1610 put this here as a record of what was covered in chapter 4 and maybe it was evolved later in the course. But for historical reasons, I think we should keep it unless I'm reading the situation wrong.
