### ISSUE TITLE
Cookiecutter command not working

### ISSUE THREAD

**Issue by fatlumtroshani** [talkpython/excel-to-python-course#3]
Hi,
The cookiecutter command from Create a project with cookiecutter [v5/9] is not working as shown in the course. I am getting the following message:

cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.

Any idea how I can fix this?

Thanks,
Fatlum

**Comment by chris1610** [comment]
Fatlum -
Thank you for raising the issue.  For cookiecutter to work, you need to have git installed on your system. Do you have it installed?

-Chris

**Comment by fatlumtroshani** [comment]
I don't believe I do. Is it something I can get from https://git-scm.com/ ?

**Comment by chris1610** [comment]
I normally use this one - https://gitforwindows.org/

**Comment by fatlumtroshani** [comment]
Thank you. I'll give it a shot. Hopefully it works out.
